# name: Cypress Tests

# on:
#   push:
#   schedule:
#     - cron: '40 4 * * 1-5' # Run Monday to Friday at 04:40 UTC

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Install dependencies
#         run: npm install

#       - name: Start server
#         run: |
#           node server.js &
#           sleep 5

#       - name: Verify server is running
#         run: |
#           curl -f http://localhost:3000/list-skip-dates || exit 1

#       - name: Check skip dates
#         id: check-skip-dates
#         run: |
#           if [ -f skipDates.json ]; then
#             SKIP_DATES=$(cat skipDates.json | jq -r '.[]')
#             CURRENT_DATE=$(date +%Y-%m-%d)
#             for SKIP_DATE in $SKIP_DATES; do
#               if [ "$SKIP_DATE" == "$CURRENT_DATE" ]; then
#                 echo "Skipping tests on $CURRENT_DATE"
#                 exit 0
#               fi
#             done
#           fi

#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           record: true
#           parallel: true
#         env:
#           CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
#           CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
#           CYPRESS_EMP_ID: ${{ secrets.CYPRESS_EMP_ID }}
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}